
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
//  and 
// , the first 
//  terms will be:

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#include <map>
#include <set>
#include <list>
#include <cmath>
#include <ctime>
#include <deque>
#include <queue>
#include <stack>
#include <string>
#include <bitset>
#include <cstdio>
#include <limits>
#include <vector>
#include <climits>
#include <cstring>
#include <cstdlib>
#include <fstream>
#include <numeric>
#include <sstream>
#include <iostream>
#include <algorithm>
#include <unordered_map>

using namespace std;


int main(){
int first = 0;
int second = 1;
int sum = 0;
// cout<<first << "\n" << second<<"\n";
while(second <= 4000000){
    if(second % 2  == 0){
        sum = sum + second;
    }
    int next = first + second;
    first = second;
    second = next;
}
cout<<"the sum of all the even fibonacci nos is : "<<sum;

    return 0;
}



